config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#spage1'
  get 'home' => 'static_pages#spage1'
  get  'spage2' => 'static_pages#spage2'
  get  'spage3' => 'static_pages#spage3'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :items do
    collection { post :import }
  end  
end

app/models/item.rb
class Item < ActiveRecord::Base
  
  #RelationShips
  belongs_to :user
  
  #Callbacks
  before_create :calculate_all_values
  before_update :calculate_all_values
  
  #Validations
  validates :item_code, presence: true, length: { maximum: 20 }
  validates :description, presence: true, length: { maximum: 50 }
  validates :cost, presence: true,  numericality: {greater_than_or_equal_to: 0}
  validates :location, presence: true, length: { maximum: 10 }
  validates :uom, presence: true, length: { maximum: 10 }
  validates :service_level, presence: true,  numericality: {greater_than: 0, less_than: 1}
  validates :lead_time, presence: true,  numericality: {greater_than_or_equal_to: 0}
  validates :lead_time_variability, presence: true,  numericality: {greater_than_or_equal_to: 0}
  validates :df1, presence: true,  numericality: {greater_than_or_equal_to: 0}
  validates :df2, presence: true,  numericality: {greater_than_or_equal_to: 0}
  validates :df3, presence: true,  numericality: {greater_than_or_equal_to: 0}
  validates :df4, presence: true,  numericality: {greater_than_or_equal_to: 0}
  validates :df5, presence: true,  numericality: {greater_than_or_equal_to: 0}
  validates :df6, presence: true,  numericality: {greater_than_or_equal_to: 0}
  validates :df7, presence: true,  numericality: {greater_than_or_equal_to: 0}
  validates :df8, presence: true,  numericality: {greater_than_or_equal_to: 0}
  validates :df9, presence: true,  numericality: {greater_than_or_equal_to: 0}
  validates :df10, presence: true,  numericality: {greater_than_or_equal_to: 0}
  validates :df11, presence: true,  numericality: {greater_than_or_equal_to: 0}
  validates :df12, presence: true,  numericality: {greater_than_or_equal_to: 0}
  validates :as1, presence: true,  numericality: {greater_than_or_equal_to: 0}
  validates :as2, presence: true,  numericality: {greater_than_or_equal_to: 0}
  validates :as3, presence: true,  numericality: {greater_than_or_equal_to: 0}
  validates :as4, presence: true,  numericality: {greater_than_or_equal_to: 0}
  validates :as5, presence: true,  numericality: {greater_than_or_equal_to: 0}
  validates :as6, presence: true,  numericality: {greater_than_or_equal_to: 0}
  validates :hf1, presence: true,  numericality: {greater_than_or_equal_to: 0}
  validates :hf2, presence: true,  numericality: {greater_than_or_equal_to: 0}
  validates :hf3, presence: true,  numericality: {greater_than_or_equal_to: 0}
  validates :hf4, presence: true,  numericality: {greater_than_or_equal_to: 0}
  validates :hf5, presence: true,  numericality: {greater_than_or_equal_to: 0}
  validates :hf6, presence: true,  numericality: {greater_than_or_equal_to: 0}
  validates :ordered_quantity, presence: true,  numericality: {greater_than_or_equal_to: 0}
  validates :actual_quantity, presence: true,  numericality: {greater_than_or_equal_to: 0}

  #Check if all items in CSV are valid
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      item = Item.new(row.to_hash)
      # exit from the block if item is not valid
      return false unless item.valid?
    end  
  end
   
  #If ALL items in CSV are valid, save all of them
  def self.import1(file)
    CSV.foreach(file.path, headers: true) do |row|
      item = Item.new(row.to_hash)
      # exit from the block if item is not valid
      return false unless item.valid?
      # save the item only if is valid
      item.save
    end  
  end

  private
  
  A1 =  -39.6968302866538
  A2 =  220.946098424521
  A3 = -275.928510446969
  A4 =  138.357751867269
  A5 =  -30.6647980661472
  A6 =    2.50662827745924
  B1 =  -54.4760987982241
  B2 =   161.585836858041
  B3 = -155.698979859887
  B4 =   66.8013118877197 
  B5 =  -13.2806815528857 
  C1 =   -7.78489400243029E-03
  C2 =   -0.322396458041136 
  C3 =   -2.40075827716184 
  C4 =   -2.54973253934373
  C5 =    4.37466414146497 
  C6 =    2.93816398269878 
  D1 =    7.78469570904146E-03
  D2 =    0.32246712907004 
  D3 =    2.445134137143 
  D4 =    3.75440866190742
  P_low = 0.02425 
  P_high = 1 - P_low

  def calculate_all_values
    
    self.mape = (((self.as1-self.hf1).abs + (self.as2-self.hf2).abs + (self.as3-self.hf3).abs + (self.as4-self.hf4).abs + (self.as5-self.hf5).abs + (self.as6-self.hf6).abs).to_f/(as1 + as2 + as3 + as4 + as5 + as6)).round(3) 
    self.bias = (((self.hf1-self.as1) + (self.hf2-self.as2) + (self.hf3-self.as3) + (self.hf4-self.as4) + (self.hf5-self.as5) + (self.hf6-self.as6)).to_f/(as1 + as2 + as3 + as4 + as5 + as6)).round(3)
    self.supply_uncertainty = ((self.ordered_quantity - self.actual_quantity).to_f/self.ordered_quantity).round(3)
    self.transit_time_variability = ((self.lead_time_variability).to_f/self.lead_time).round(3)
    
    def phi(p)
      raise ArgumentError if p < 0 || p > 1
      if p < P_low
        q = (-2 * Math::log(p))**0.5
        (((((C1 * q + C2) * q + C3) * q + C4) * q + C5) * q + C6) / 
        ((((D1 * q + D2) * q + D3) * q + D4) * q + 1)
      elsif p <= P_high
        q = p - 0.5
        r = q * q
        (((((A1 * r + A2) * r + A3) * r + A4) * r + A5) * r + A6) * q / 
        (((((B1 * r + B2) * r + B3) * r + B4) * r + B5) * r + 1)
      else
        q = (-2 * Math::log(1 - p))**0.5
        (((((C1 * q + C2) * q + C3) * q + C4) * q + C5) * q + C6) / 
        ((((D1 * q + D2) * q + D3) * q + D4) * q + 1)
      end
    end
    
    self.safety_stock = (phi(self.service_level) * (self.mape**2 + (self.transit_time_variability**2 + self.supply_uncertainty**2)**0.5)**0.5 * self.lead_time).round(3) - (self.lead_time * self.bias).round(3) 
    
    self.safety_stock_1 = (self.safety_stock * (self.df1 + self.df2 + self.df3 + self.df4)/28).round(3)
    self.safety_stock_2 = (self.safety_stock * (self.df5 + self.df6 + self.df7 + self.df8)/28).round(3)
    self.safety_stock_3 = (self.safety_stock * (self.df9 + self.df10 + self.df11 + self.df12)/28).round(3)
  end  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :show, :edit]
  before_action :correct_user,   only: :destroy

  def index
    @items = current_user.items
    respond_to do |format|
      format.html
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"item-list.csv\""
        headers['Content-Type'] ||= 'text/csv'
      end
      format.json {  render json: @items}
      format.xml {  render xml: @items}
    end  
  end
  
  def create
    @item = current_user.items.build(item_params)
    if @item.save
      flash[:success] = "Inventory Item created. View Analysis below."
      redirect_to item_path(@item)
    else
      render 'static_pages/spage2'
    end
  end

  def show
    @item = Item.find(params[:id])
    if @item.user_id != current_user.id #If a user is trying to view the show page of an item that doesn't belong to him, take him to Home page
      render 'static_pages/spage1'
    end  
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    if @item.update_attributes(item_params)
      flash[:success] = "Item Attributes updated"
      redirect_to @item
    else
      render 'edit'
    end
  end
  
  #Import from CSV feature
  def import
    if current_user.items.import(params[:file]) == false
      #False encountered means atleast one invalid item
      flash[:danger] = "Error Encountered. No Items Imported. Please check CSV File."
      redirect_to spage3_path
    else 
      #True means all valid items so save all of them
      current_user.items.import1(params[:file])
      flash[:success] = "All Items Imported Successfully."
      redirect_to spage3_path
    end
  end 
  
  def destroy
    @item.destroy
    flash[:success] = "Item deleted"
    redirect_to current_user
  end
  
  private

    def item_params
      params.require(:item).permit(:item_code, :description, :cost, :location, :uom, :service_level, :lead_time, :lead_time_variability, :df1, :df2, :df3, :df4, :df5, :df6, :df7, :df8, :df9, :df10, :df11, :df12, :as1, :as2, :as3, :as4, :as5, :as6, :hf1, :hf2, :hf3, :hf4, :hf5, :hf6, :ordered_quantity, :actual_quantity)
    end
    
    def correct_user
      @item = current_user.items.find_by(id: params[:id])
      redirect_to root_url if @item.nil?
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_item.html.erb
<tr>
  <td></td>
  <td><%= item.item_code %></td>
  <td><%= item.description %></td>
  <td><%= link_to "Dashboard", item_path(item) %></td>
  <td><%= link_to "Edit", edit_item_path(item) %></td>
  <td>
    <% if current_user?(item.user) %>
      <%= link_to "Delete Item", item, method: :delete, data: { confirm: "You sure?" } %>
    <% end %>  
  </td>
<tr>

app/views/items/edit.html.erb
<h3 style="margin-top: 90px">Edit Inventory Item</h3>
<hr style="margin-top: 0; margin-bottom: 60px;">

<%= form_for(@item) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
    
    <!-- Section 1. Item Information -->
    
    <h4>Section 1. Item Information</h4>
    <hr style="margin-top: 0"> 

    <div class="row">
      <div class="col-md-3">
        <div class="form-group">
          <%= f.text_field :item_code, class: "form-control", placeholder: "Item Code (Must be unique)" %>
        </div>
      </div>
      <div class="col-md-3">
        <div class="form-group">
          <%= f.text_field :description, class: "form-control", placeholder: "Description" %>
        </div> 
      </div>
      <div class="col-md-3">
        <div class="form-group">
          <%= f.text_field :location, class: "form-control", placeholder: "Location" %>
        </div>
      </div>
      <div class="col-md-3">
        <div class="form-group">
          <%= f.text_field :uom, class: "form-control", placeholder: "Unit of measure (eg. eaches, lbs, kgs)" %>
        </div>
      </div>
    </div><!--First row -->
    
    <div class="row">
      <div class="col-md-3">
        <div class="form-group">
          <%= f.number_field :cost, class: "form-control", placeholder: "Cost (in Dollars)", step: "any" %>
        </div>
      </div>
      <div class="col-md-3">
        <div class="form-group">
          <%= f.number_field :service_level, class: "form-control", placeholder: "Service Level (must be 0<p>1)", step: "any" %>
        </div>
      </div>
      <div class="col-md-3">
        <div class="form-group">
          <%= f.number_field :lead_time, class: "form-control", placeholder: "Lead Time (in Days)", step: "any" %>
        </div>
      </div>
      <div class="col-md-3">
        <div class="form-group">
          <%= f.number_field :lead_time_variability, class: "form-control", placeholder: "Lead Time Variability (in Days)", step: "any" %>
        </div> 
      </div>
    </div><!--Second row -->
    
    <!-- Section 2. Demand Forecast -->
    
    <h4>Section 2. Demand Forecast for 12 Weeks</h4>
    <hr style="margin-top: 0">
    
    <div class-"row">
      <div class="col-md-2">
        <div class="form-group">
          <%= f.number_field :df1, class: "form-control", placeholder: "Week 1", step: "any" %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <%= f.number_field :df2, class: "form-control", placeholder: "Week 2", step: "any" %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <%= f.number_field :df3, class: "form-control", placeholder: "Week 3", step: "any" %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <%= f.number_field :df4, class: "form-control", placeholder: "Week 4", step: "any" %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <%= f.number_field :df5, class: "form-control", placeholder: "Week 5", step: "any" %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <%= f.number_field :df6, class: "form-control", placeholder: "Week 6", step: "any" %>
        </div>
      </div>
    </div><!-- end First row -->
    
    <div class-"row">
      <div class="col-md-2">
        <div class="form-group">
          <%= f.number_field :df7, class: "form-control", placeholder: "Week 7", step: "any" %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <%= f.number_field :df8, class: "form-control", placeholder: "Week 8", step: "any" %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <%= f.number_field :df9, class: "form-control", placeholder: "Week 9", step: "any" %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <%= f.number_field :df10, class: "form-control", placeholder: "Week 10", step: "any" %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <%= f.number_field :df11, class: "form-control", placeholder: "Week 11", step: "any" %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <%= f.number_field :df12, class: "form-control", placeholder: "Week 12", step: "any" %>
        </div>
      </div>
    </div><!-- end Second row -->
    
    <!-- Section 3. Historical Data -->
    
    <h4>Section 3. Historical Sales Data</h4>
    <hr style="margin-top: 0">
    
    <div class="row">
      <div class="col-md-2">  
        <div class="form-group">
          <%= f.number_field :as1, class: "form-control", placeholder: "A. Sales Month 1", step: "any" %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <%= f.number_field :as2, class: "form-control", placeholder: "A. Sales Month 2", step: "any" %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <%= f.number_field :as3, class: "form-control", placeholder: "A. Sales Month 3", step: "any" %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <%= f.number_field :as4, class: "form-control", placeholder: "A. Sales Month 4", step: "any" %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <%= f.number_field :as5, class: "form-control", placeholder: "A. Sales Month 5", step: "any" %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <%= f.number_field :as6, class: "form-control", placeholder: "A. Sales Month 6", step: "any" %>
        </div>
      </div>
    </div><!-- end first row -->
    
    <div class="row">
      <div class="col-md-2">  
        <div class="form-group">
          <%= f.number_field :hf1, class: "form-control", placeholder: "H. Forecast Month 1", step: "any" %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <%= f.number_field :hf2, class: "form-control", placeholder: "H. Forecast Month 2", step: "any" %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <%= f.number_field :hf3, class: "form-control", placeholder: "H. Forecast Month 3", step: "any" %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <%= f.number_field :hf4, class: "form-control", placeholder: "H. Forecast Month 4", step: "any" %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <%= f.number_field :hf5, class: "form-control", placeholder: "H. Forecast Month 5", step: "any" %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <%= f.number_field :hf6, class: "form-control", placeholder: "H. Forecast Month 6", step: "any" %>
        </div>
      </div>
    </div><!-- end Section 3. Historical Sales Data -->
    
    <!-- Section 4. Supply -->
    
    <h4>Section 4. Supply</h4>
    <hr style="margin-top: 0">
    
    <div class="row">
      <div class="col-md-2">  
        <div class="form-group">
          <%= f.number_field :ordered_quantity, class: "form-control", placeholder: "Ordered Quantity", step: "any" %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <%= f.number_field :actual_quantity, class: "form-control", placeholder: "Actual Quantity", step: "any" %>
        </div>
      </div>
    </div><!-- end Section 4. Supply -->
    
    <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/items/index.csv.erb
<%- headers = ['Item_Code', 'Description', 'Cost', 'Location', 'Unit of Measure', 'Service Level', 'Lead Time', 'Lead Time Variability', 'Demand Forecast Week 1', 'Demand Forecast Week 2', 'Demand Forecast Week 3', 'Demand Forecast Week 4', 'Demand Forecast Week 5', 'Demand Forecast Week 6', 'Demand Forecast Week 7', 'Demand Forecast Week 8', 'Demand Forecast Week 9', 'Demand Forecast Week 10', 'Demand Forecast Week 11', 'Demand Forecast Week 12', 'Acual Sales Month 1',  'Acual Sales Month 2', 'Acual Sales Month 3',  'Acual Sales Month 4',  'Acual Sales Month 5',  'Acual Sales Month 6', 'Hitorical Forecast Month 1', 'Hitorical Forecast Month 2', 'Hitorical Forecast Month 3', 'Hitorical Forecast Month 4', 'Hitorical Forecast Month 5', 'Hitorical Forecast Month 6', 'Ordered Quantity', 'Actual Quantity',  'Mape', 'Bias', 'Supply Uncertainty', 'Transit Time Variability', 'Safety Stock in Days', 'Safety Stock Week 1-4', 'Safety Stock Week 5-8', 'Safety Stock Week 9-12' ] -%>
<%= CSV.generate_line headers %>
<%- @items.each do |item| -%>
<%= CSV.generate_line([item.item_code, item.description, item.cost, item.location, item.uom, item.service_level, item.lead_time, item.lead_time_variability, item.df1, item.df2, item.df3, item.df4, item.df5, item.df6, item.df7, item.df8, item.df9, item.df10, item.df11, item.df12, item.as1, item.as2, item.as3, item.as4, item.as5, item.as6, item.hf1, item.hf2, item.hf3, item.hf4, item.hf5, item.hf6, item.ordered_quantity, item.actual_quantity, item.mape, item.bias, item.supply_uncertainty, item.transit_time_variability, item.safety_stock, item.safety_stock_1, item.safety_stock_2, item.safety_stock_3]) -%>
<%- end -%>