config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#spage1'
  get 'home' => 'static_pages#spage1'
  get  'spage2' => 'static_pages#spage2'
  get  'spage3' => 'static_pages#spage3'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :items do
    collection { post :import }
  end  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InSight</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--<%= favicon_link_tag 'cognizant_favicon.ico' %>-->
  <script src="https://code.highcharts.com/modules/exporting.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
</head>

<body>

  <div class="container" id="main">

    <div class="navbar navbar-fixed-top navbar-default">
      <div class="container">
        
        <a class="navbar-brand" href="/">InSight</a>
        <% if logged_in? %>
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to "Home", root_path %></li>
          </ul><!-- end nav left -->
        <% else %>
        <% end %>
                   
        <ul class="nav navbar-nav pull-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
								<li><a><small> Logged in as</small><br><strong><%= current_user.name %></strong></a></li>
								<li class="divider"></li>									
								<li><%= link_to '<i class="glyphicon glyphicon-refresh"></i> Your Account'.html_safe, edit_user_path(current_user) %></li>									
								<li><a href="#"><span class="glyphicon glyphicon-briefcase"></span> Billing</a></li>									
								<li class="divider"></li>									
								<li><%= link_to '<i class="glyphicon glyphicon-off"></i> Logout'.html_safe, logout_path, method: "delete" %></li>
						</ul>
          </li>  
        <% else %>
          <li><a href="#about">About</a></li>
          <li><a href="#services">Services</a></li>
          <li><a href="#contact">Contact</a></li>
        <% end %>
        </ul><!-- end nav right -->
                   
      </div><!-- end navbar container -->
    </div><!-- end navbar -->

    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>" id="greenAlert"><%= message %></div>
    <% end %>
    
<%= yield %>
<%= debug(params) if Rails.env.development? %>      
  </div><!-- end main container -->

  <footer class="footer">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <p class="copyright text-muted small">Copyright &copy; Cognizant Technology Solutions. All Rights Reserved</p>
        </div>
        <div class="col-md-6">
          <%= image_tag("Cognizant3.png", alt: "Cognizant Logo", align: "right") %>
        </div>
      </div>
    </div>  
  </footer>
  
</body>
</html>